<?php

use Illuminate\Database\Seeder;

class CustomersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('customers')->delete();
        
        \DB::table('customers')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'Murilo Eduardo dos Santos',
                'email' => 'muriloeduardoooooo@gmail.com',
                'phone' => '51996824735',
                'cpf' => '02237841098',
                'birth_day' => '1995-02-02',
                'emergency_phone' => '51997345019',
                'cep' => '90010221',
                'neighborhood' => 'Centro Histórico',
                'street' => 'Av. Senador Salgado Filho',
                'created_at' => '2018-03-22 16:03:42',
                'updated_at' => '2018-03-25 22:42:14',
                'number' => 359,
                'created_id' => 0,
                'professional_id' => 1,
                'sannyas' => 'Nisargam',
                'updated_id' => 1,
                'type_id' => 1,
                'how_did_find_out_id' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'Vinicius dos Santos',
                'email' => 'vinicius@gmail.com',
                'phone' => NULL,
                'cpf' => NULL,
                'birth_day' => NULL,
                'emergency_phone' => NULL,
                'cep' => NULL,
                'neighborhood' => NULL,
                'street' => NULL,
                'created_at' => '2018-03-22 19:24:33',
                'updated_at' => '2018-03-23 15:32:41',
                'number' => NULL,
                'created_id' => 0,
                'professional_id' => 2,
                'sannyas' => NULL,
                'updated_id' => 0,
                'type_id' => NULL,
                'how_did_find_out_id' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'Pedro Paulo',
                'email' => 'pedro.paulo@gmail.com',
                'phone' => NULL,
                'cpf' => NULL,
                'birth_day' => NULL,
                'emergency_phone' => NULL,
                'cep' => NULL,
                'neighborhood' => NULL,
                'street' => NULL,
                'created_at' => '2018-03-22 19:24:59',
                'updated_at' => '2018-03-22 19:24:59',
                'number' => NULL,
                'created_id' => 0,
                'professional_id' => 0,
                'sannyas' => NULL,
                'updated_id' => 0,
                'type_id' => NULL,
                'how_did_find_out_id' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'Regina Cazé',
                'email' => 'regina@gmail.com',
                'phone' => '9999999999999',
                'cpf' => '999999999',
                'birth_day' => '1991-01-01',
                'emergency_phone' => '9999999999999',
                'cep' => '99999999',
                'neighborhood' => 'Centro',
                'street' => 'Rua das Pedras',
                'created_at' => '2018-03-23 12:34:25',
                'updated_at' => '2018-03-23 12:34:25',
                'number' => 2,
                'created_id' => 4,
                'professional_id' => 0,
                'sannyas' => NULL,
                'updated_id' => 0,
                'type_id' => NULL,
                'how_did_find_out_id' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'Ana Maria Braga',
                'email' => 'ana@gmail.com',
                'phone' => '121212',
                'cpf' => NULL,
                'birth_day' => NULL,
                'emergency_phone' => NULL,
                'cep' => NULL,
                'neighborhood' => NULL,
                'street' => NULL,
                'created_at' => '2018-03-23 12:35:32',
                'updated_at' => '2018-03-23 19:42:43',
                'number' => NULL,
                'created_id' => 1,
                'professional_id' => 1,
                'sannyas' => 'Prema',
                'updated_id' => 1,
                'type_id' => 2,
                'how_did_find_out_id' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'Maria Cecilia',
                'email' => 'maria@gmail.com',
                'phone' => NULL,
                'cpf' => NULL,
                'birth_day' => NULL,
                'emergency_phone' => NULL,
                'cep' => NULL,
                'neighborhood' => NULL,
                'street' => NULL,
                'created_at' => '2018-03-23 15:30:18',
                'updated_at' => '2018-03-24 23:46:05',
                'number' => NULL,
                'created_id' => 1,
                'professional_id' => 2,
                'sannyas' => 'asdas',
                'updated_id' => 1,
                'type_id' => 1,
                'how_did_find_out_id' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'Abelardo Barbosa',
                'email' => NULL,
                'phone' => NULL,
                'cpf' => NULL,
                'birth_day' => NULL,
                'emergency_phone' => NULL,
                'cep' => NULL,
                'neighborhood' => NULL,
                'street' => NULL,
                'created_at' => '2018-03-24 23:46:40',
                'updated_at' => '2018-03-24 23:46:40',
                'number' => NULL,
                'created_id' => 1,
                'professional_id' => 3,
                'sannyas' => NULL,
                'updated_id' => 1,
                'type_id' => 2,
                'how_did_find_out_id' => NULL,
            ),
            7 => 
            array (
                'id' => 9,
                'name' => 'Rapidão da Silva',
                'email' => NULL,
                'phone' => NULL,
                'cpf' => NULL,
                'birth_day' => NULL,
                'emergency_phone' => NULL,
                'cep' => NULL,
                'neighborhood' => NULL,
                'street' => NULL,
                'created_at' => '2018-03-25 01:18:53',
                'updated_at' => '2018-03-25 01:18:53',
                'number' => NULL,
                'created_id' => 1,
                'professional_id' => NULL,
                'sannyas' => NULL,
                'updated_id' => 1,
                'type_id' => NULL,
                'how_did_find_out_id' => NULL,
            ),
            8 => 
            array (
                'id' => 10,
                'name' => 'Rapidão da Silva com Telefone',
                'email' => NULL,
                'phone' => '9999999999999',
                'cpf' => NULL,
                'birth_day' => NULL,
                'emergency_phone' => NULL,
                'cep' => NULL,
                'neighborhood' => NULL,
                'street' => NULL,
                'created_at' => '2018-03-25 01:19:17',
                'updated_at' => '2018-03-25 01:19:17',
                'number' => NULL,
                'created_id' => 1,
                'professional_id' => NULL,
                'sannyas' => NULL,
                'updated_id' => 1,
                'type_id' => NULL,
                'how_did_find_out_id' => NULL,
            ),
            9 => 
            array (
                'id' => 13,
                'name' => 'Manoel Barcelos',
                'email' => NULL,
                'phone' => '9829182981921',
                'cpf' => NULL,
                'birth_day' => NULL,
                'emergency_phone' => NULL,
                'cep' => NULL,
                'neighborhood' => NULL,
                'street' => NULL,
                'created_at' => '2018-03-25 20:38:41',
                'updated_at' => '2018-03-26 01:14:49',
                'number' => NULL,
                'created_id' => 1,
                'professional_id' => 1,
                'sannyas' => NULL,
                'updated_id' => 1,
                'type_id' => 1,
                'how_did_find_out_id' => NULL,
            ),
            10 => 
            array (
                'id' => 14,
                'name' => 'Paola Silva',
                'email' => NULL,
                'phone' => '111111111',
                'cpf' => NULL,
                'birth_day' => NULL,
                'emergency_phone' => NULL,
                'cep' => NULL,
                'neighborhood' => NULL,
                'street' => NULL,
                'created_at' => '2018-03-25 20:38:59',
                'updated_at' => '2018-03-25 22:47:24',
                'number' => NULL,
                'created_id' => 1,
                'professional_id' => 2,
                'sannyas' => NULL,
                'updated_id' => 1,
                'type_id' => 3,
                'how_did_find_out_id' => NULL,
            ),
            11 => 
            array (
                'id' => 15,
                'name' => 'João Nair Ribeiro',
                'email' => NULL,
                'phone' => NULL,
                'cpf' => NULL,
                'birth_day' => NULL,
                'emergency_phone' => NULL,
                'cep' => NULL,
                'neighborhood' => NULL,
                'street' => NULL,
                'created_at' => '2018-03-25 22:34:05',
                'updated_at' => '2018-03-25 22:44:49',
                'number' => NULL,
                'created_id' => 1,
                'professional_id' => 4,
                'sannyas' => NULL,
                'updated_id' => 1,
                'type_id' => 1,
                'how_did_find_out_id' => NULL,
            ),
            12 => 
            array (
                'id' => 16,
                'name' => 'Cliente com Anexos',
                'email' => NULL,
                'phone' => NULL,
                'cpf' => NULL,
                'birth_day' => NULL,
                'emergency_phone' => NULL,
                'cep' => NULL,
                'neighborhood' => NULL,
                'street' => NULL,
                'created_at' => '2018-03-26 06:58:12',
                'updated_at' => '2018-03-26 07:07:47',
                'number' => NULL,
                'created_id' => 1,
                'professional_id' => 1,
                'sannyas' => NULL,
                'updated_id' => 1,
                'type_id' => 1,
                'how_did_find_out_id' => NULL,
            ),
            13 => 
            array (
                'id' => 17,
                'name' => 'cliente feito com ajax',
                'email' => NULL,
                'phone' => NULL,
                'cpf' => NULL,
                'birth_day' => NULL,
                'emergency_phone' => NULL,
                'cep' => NULL,
                'neighborhood' => NULL,
                'street' => NULL,
                'created_at' => '2018-04-12 05:11:51',
                'updated_at' => '2018-04-12 05:11:51',
                'number' => NULL,
                'created_id' => 1,
                'professional_id' => NULL,
                'sannyas' => NULL,
                'updated_id' => 1,
                'type_id' => NULL,
                'how_did_find_out_id' => NULL,
            ),
            14 => 
            array (
                'id' => 18,
                'name' => 'mais um cliente feito com ajax',
                'email' => NULL,
                'phone' => NULL,
                'cpf' => NULL,
                'birth_day' => NULL,
                'emergency_phone' => NULL,
                'cep' => NULL,
                'neighborhood' => NULL,
                'street' => NULL,
                'created_at' => '2018-04-12 05:12:03',
                'updated_at' => '2018-04-12 05:12:03',
                'number' => NULL,
                'created_id' => 1,
                'professional_id' => NULL,
                'sannyas' => NULL,
                'updated_id' => 1,
                'type_id' => NULL,
                'how_did_find_out_id' => NULL,
            ),
            15 => 
            array (
                'id' => 19,
                'name' => 'cliente feito do cel android',
                'email' => NULL,
                'phone' => NULL,
                'cpf' => NULL,
                'birth_day' => NULL,
                'emergency_phone' => NULL,
                'cep' => NULL,
                'neighborhood' => NULL,
                'street' => NULL,
                'created_at' => '2018-04-12 18:13:57',
                'updated_at' => '2018-04-12 18:13:57',
                'number' => NULL,
                'created_id' => 1,
                'professional_id' => NULL,
                'sannyas' => NULL,
                'updated_id' => 1,
                'type_id' => 3,
                'how_did_find_out_id' => NULL,
            ),
        ));
        
        
    }
}