<?php

use Illuminate\Database\Seeder;

class DataRowsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('data_rows')->delete();
        
        \DB::table('data_rows')->insert(array (
            0 => 
            array (
                'id' => 26,
                'data_type_id' => 3,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 1,
            ),
            1 => 
            array (
                'id' => 27,
                'data_type_id' => 3,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Nome',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 3,
            ),
            2 => 
            array (
                'id' => 28,
                'data_type_id' => 3,
                'field' => 'email',
                'type' => 'text',
                'display_name' => 'Email',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 4,
            ),
            3 => 
            array (
                'id' => 29,
                'data_type_id' => 3,
                'field' => 'password',
                'type' => 'password',
                'display_name' => 'Senha',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => NULL,
                'order' => 5,
            ),
            4 => 
            array (
                'id' => 30,
                'data_type_id' => 3,
                'field' => 'user_belongsto_role_relationship',
                'type' => 'relationship',
                'display_name' => 'Função',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"model":"TCG\\\\Voyager\\\\Models\\\\Role","table":"roles","type":"belongsTo","column":"role_id","key":"id","label":"display_name","pivot_table":"roles","pivot":"0"}',
                'order' => 7,
            ),
            5 => 
            array (
                'id' => 31,
                'data_type_id' => 3,
                'field' => 'remember_token',
                'type' => 'text',
                'display_name' => 'remember_token',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 6,
            ),
            6 => 
            array (
                'id' => 32,
                'data_type_id' => 3,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Criado em',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{"format":"%d/%m/%Y %X"}',
                'order' => 10,
            ),
            7 => 
            array (
                'id' => 33,
                'data_type_id' => 3,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Editado Em',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{"format":"%d/%m/%Y %X"}',
                'order' => 13,
            ),
            8 => 
            array (
                'id' => 35,
                'data_type_id' => 5,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 1,
            ),
            9 => 
            array (
                'id' => 36,
                'data_type_id' => 5,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 2,
            ),
            10 => 
            array (
                'id' => 37,
                'data_type_id' => 5,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'created_at',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 3,
            ),
            11 => 
            array (
                'id' => 38,
                'data_type_id' => 5,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'updated_at',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 4,
            ),
            12 => 
            array (
                'id' => 46,
                'data_type_id' => 6,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 1,
            ),
            13 => 
            array (
                'id' => 47,
                'data_type_id' => 6,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 2,
            ),
            14 => 
            array (
                'id' => 48,
                'data_type_id' => 6,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'created_at',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 3,
            ),
            15 => 
            array (
                'id' => 49,
                'data_type_id' => 6,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'updated_at',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 4,
            ),
            16 => 
            array (
                'id' => 50,
                'data_type_id' => 6,
                'field' => 'display_name',
                'type' => 'text',
                'display_name' => 'Display Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 5,
            ),
            17 => 
            array (
                'id' => 53,
                'data_type_id' => 3,
                'field' => 'role_id',
                'type' => 'text',
                'display_name' => 'Função ID',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 8,
            ),
            18 => 
            array (
                'id' => 67,
                'data_type_id' => 8,
                'field' => 'id',
                'type' => 'checkbox',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 1,
            ),
            19 => 
            array (
                'id' => 68,
                'data_type_id' => 8,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Nome',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 2,
            ),
            20 => 
            array (
                'id' => 72,
                'data_type_id' => 8,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Criado em',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{"format":"%d/%m/%Y %X"}',
                'order' => 6,
            ),
            21 => 
            array (
                'id' => 73,
                'data_type_id' => 8,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Editado em',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{"format":"%d/%m/%Y %X"}',
                'order' => 8,
            ),
            22 => 
            array (
                'id' => 83,
                'data_type_id' => 9,
                'field' => 'id',
                'type' => 'checkbox',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 1,
            ),
            23 => 
            array (
                'id' => 84,
                'data_type_id' => 9,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Nome',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 2,
            ),
            24 => 
            array (
                'id' => 85,
                'data_type_id' => 9,
                'field' => 'sannyas',
                'type' => 'text',
                'display_name' => 'Sannyas',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 3,
            ),
            25 => 
            array (
                'id' => 87,
                'data_type_id' => 9,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Criado em',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{"format":"%d/%m/%Y %X"}',
                'order' => 6,
            ),
            26 => 
            array (
                'id' => 88,
                'data_type_id' => 9,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Editado em',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{"format":"%d/%m/%Y %X"}',
                'order' => 9,
            ),
            27 => 
            array (
                'id' => 89,
                'data_type_id' => 9,
                'field' => 'therapist_hasmany_customer_relationship',
                'type' => 'relationship',
                'display_name' => 'Clientes',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Customer","table":"customers","type":"belongsToMany","column":"id","key":"id","label":"name","pivot_table":"therapist_customer","pivot":"1"}',
                'order' => 4,
            ),
            28 => 
            array (
                'id' => 94,
                'data_type_id' => 9,
                'field' => 'therapist_belongsto_user_relationship',
                'type' => 'relationship',
                'display_name' => 'Criado por',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{"model":"App\\\\User","table":"users","type":"belongsTo","column":"created_id","key":"id","label":"name","pivot_table":"customers","pivot":"0"}',
                'order' => 5,
            ),
            29 => 
            array (
                'id' => 95,
                'data_type_id' => 9,
                'field' => 'created_id',
                'type' => 'hidden',
                'display_name' => 'Created Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 7,
            ),
            30 => 
            array (
                'id' => 97,
                'data_type_id' => 10,
                'field' => 'id',
                'type' => 'checkbox',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 1,
            ),
            31 => 
            array (
                'id' => 98,
                'data_type_id' => 10,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Nome',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rules":["required"],"messages":{"required":"Campo :attribute é obrigatório."}},"display":{"width":"6"}}',
                'order' => 2,
            ),
            32 => 
            array (
                'id' => 99,
                'data_type_id' => 10,
                'field' => 'email',
                'type' => 'text',
                'display_name' => 'Email',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 5,
            ),
            33 => 
            array (
                'id' => 100,
                'data_type_id' => 10,
                'field' => 'phone',
                'type' => 'text',
                'display_name' => 'Telefone',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"display":{"width":"6"}}',
                'order' => 6,
            ),
            34 => 
            array (
                'id' => 101,
                'data_type_id' => 10,
                'field' => 'cpf',
                'type' => 'text',
                'display_name' => 'CPF',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 8,
            ),
            35 => 
            array (
                'id' => 102,
                'data_type_id' => 10,
                'field' => 'birth_day',
                'type' => 'date',
                'display_name' => 'Data de nascimento',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"format":"%d/%m/%Y %X"}',
                'order' => 9,
            ),
            36 => 
            array (
                'id' => 103,
                'data_type_id' => 10,
                'field' => 'emergency_phone',
                'type' => 'text',
                'display_name' => 'Telefone para emergência',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"display":{"width":"6"}}',
                'order' => 7,
            ),
            37 => 
            array (
                'id' => 104,
                'data_type_id' => 10,
                'field' => 'cep',
                'type' => 'text',
                'display_name' => 'CEP',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"display":{"width":"3"}}',
                'order' => 10,
            ),
            38 => 
            array (
                'id' => 105,
                'data_type_id' => 10,
                'field' => 'neighborhood',
                'type' => 'text',
                'display_name' => 'Bairro',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"display":{"width":"3"}}',
                'order' => 11,
            ),
            39 => 
            array (
                'id' => 106,
                'data_type_id' => 10,
                'field' => 'street',
                'type' => 'text',
                'display_name' => 'Endereço',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"display":{"width":"3"}}',
                'order' => 12,
            ),
            40 => 
            array (
                'id' => 107,
                'data_type_id' => 10,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Criado em',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{"format":"%d/%m/%Y %X"}',
                'order' => 17,
            ),
            41 => 
            array (
                'id' => 108,
                'data_type_id' => 10,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Editado em',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{"format":"%d/%m/%Y %X"}',
                'order' => 20,
            ),
            42 => 
            array (
                'id' => 109,
                'data_type_id' => 10,
                'field' => 'number',
                'type' => 'number',
                'display_name' => 'Número',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"display":{"width":"3"}}',
                'order' => 13,
            ),
            43 => 
            array (
                'id' => 110,
                'data_type_id' => 10,
                'field' => 'created_id',
                'type' => 'hidden',
                'display_name' => 'Created Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 22,
            ),
            44 => 
            array (
                'id' => 112,
                'data_type_id' => 10,
                'field' => 'sannyas',
                'type' => 'text',
                'display_name' => 'Sannyas',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"display":{"width":"6"}}',
                'order' => 3,
            ),
            45 => 
            array (
                'id' => 114,
                'data_type_id' => 10,
                'field' => 'customer_belongsto_user_relationship',
                'type' => 'relationship',
                'display_name' => 'Criado por',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{"model":"App\\\\User","table":"users","type":"belongsTo","column":"created_id","key":"id","label":"name","pivot_table":"customers","pivot":"0"}',
                'order' => 16,
            ),
            46 => 
            array (
                'id' => 115,
                'data_type_id' => 10,
                'field' => 'customer_belongsto_therapist_relationship',
                'type' => 'relationship',
                'display_name' => 'Terapeuta',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Professional","table":"professionals","type":"belongsTo","column":"professional_id","key":"id","label":"sannyas","pivot_table":"customers","pivot":"0"}',
                'order' => 15,
            ),
            47 => 
            array (
                'id' => 116,
                'data_type_id' => 10,
                'field' => 'customer_belongsto_user_relationship_1',
                'type' => 'relationship',
                'display_name' => 'Editado por último por',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{"model":"App\\\\User","table":"users","type":"belongsTo","column":"updated_id","key":"id","label":"name","pivot_table":"customers","pivot":"0"}',
                'order' => 18,
            ),
            48 => 
            array (
                'id' => 117,
                'data_type_id' => 10,
                'field' => 'updated_id',
                'type' => 'hidden',
                'display_name' => 'Updated Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 21,
            ),
            49 => 
            array (
                'id' => 120,
                'data_type_id' => 9,
                'field' => 'therapist_belongsto_user_relationship_1',
                'type' => 'relationship',
                'display_name' => 'Editado por último por',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{"model":"App\\\\User","table":"users","type":"belongsTo","column":"updated_id","key":"id","label":"name","pivot_table":"customers","pivot":"0"}',
                'order' => 8,
            ),
            50 => 
            array (
                'id' => 121,
                'data_type_id' => 9,
                'field' => 'updated_id',
                'type' => 'hidden',
                'display_name' => 'Updated Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 10,
            ),
            51 => 
            array (
                'id' => 126,
                'data_type_id' => 11,
                'field' => 'id',
                'type' => 'checkbox',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 1,
            ),
            52 => 
            array (
                'id' => 127,
                'data_type_id' => 11,
                'field' => 'lable',
                'type' => 'text',
                'display_name' => 'Tipo de cliente',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 2,
            ),
            53 => 
            array (
                'id' => 128,
                'data_type_id' => 11,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Criado em',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{"format":"%d/%m/%Y %X"}',
                'order' => 4,
            ),
            54 => 
            array (
                'id' => 129,
                'data_type_id' => 11,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Editado em',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{"format":"%d/%m/%Y %X"}',
                'order' => 7,
            ),
            55 => 
            array (
                'id' => 130,
                'data_type_id' => 12,
                'field' => 'id',
                'type' => 'checkbox',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 1,
            ),
            56 => 
            array (
                'id' => 131,
                'data_type_id' => 12,
                'field' => 'lable',
                'type' => 'text',
                'display_name' => 'Opção de como cliente ficou sabendo do Namastê',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 2,
            ),
            57 => 
            array (
                'id' => 132,
                'data_type_id' => 12,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Criado em',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 4,
            ),
            58 => 
            array (
                'id' => 133,
                'data_type_id' => 12,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Editado em',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 7,
            ),
            59 => 
            array (
                'id' => 134,
                'data_type_id' => 12,
                'field' => 'created_id',
                'type' => 'hidden',
                'display_name' => 'Created Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => NULL,
                'order' => 5,
            ),
            60 => 
            array (
                'id' => 135,
                'data_type_id' => 12,
                'field' => 'updated_id',
                'type' => 'hidden',
                'display_name' => 'Updated Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => NULL,
                'order' => 8,
            ),
            61 => 
            array (
                'id' => 137,
                'data_type_id' => 11,
                'field' => 'customer_type_belongsto_user_relationship',
                'type' => 'relationship',
                'display_name' => 'Criado por',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{"model":"App\\\\User","table":"users","type":"belongsTo","column":"created_id","key":"id","label":"name","pivot_table":"customer_types","pivot":"0"}',
                'order' => 3,
            ),
            62 => 
            array (
                'id' => 138,
                'data_type_id' => 11,
                'field' => 'created_id',
                'type' => 'hidden',
                'display_name' => 'Created Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 5,
            ),
            63 => 
            array (
                'id' => 139,
                'data_type_id' => 11,
                'field' => 'updated_id',
                'type' => 'hidden',
                'display_name' => 'Updated Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 8,
            ),
            64 => 
            array (
                'id' => 140,
                'data_type_id' => 11,
                'field' => 'customer_type_belongsto_user_relationship_1',
                'type' => 'relationship',
                'display_name' => 'Editado por último por',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{"model":"App\\\\User","table":"users","type":"belongsTo","column":"updated_id","key":"id","label":"name","pivot_table":"customer_types","pivot":"0"}',
                'order' => 6,
            ),
            65 => 
            array (
                'id' => 141,
                'data_type_id' => 10,
                'field' => 'type_id',
                'type' => 'hidden',
                'display_name' => 'Type Id',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => NULL,
                'order' => 19,
            ),
            66 => 
            array (
                'id' => 142,
                'data_type_id' => 10,
                'field' => 'customer_belongsto_customer_type_relationship',
                'type' => 'relationship',
                'display_name' => 'Tipo',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\CustomerType","table":"customer_types","type":"belongsTo","column":"type_id","key":"id","label":"lable","pivot_table":"customer_types","pivot":"0"}',
                'order' => 4,
            ),
            67 => 
            array (
                'id' => 143,
                'data_type_id' => 12,
                'field' => 'how_did_find_out_belongsto_user_relationship',
                'type' => 'relationship',
                'display_name' => 'Criado por',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{"model":"App\\\\User","table":"users","type":"belongsTo","column":"created_id","key":"id","label":"name","pivot_table":"customer_types","pivot":"0"}',
                'order' => 3,
            ),
            68 => 
            array (
                'id' => 144,
                'data_type_id' => 12,
                'field' => 'how_did_find_out_belongsto_user_relationship_1',
                'type' => 'relationship',
                'display_name' => 'Editado por último por',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{"model":"App\\\\User","table":"users","type":"belongsTo","column":"updated_id","key":"id","label":"name","pivot_table":"customer_types","pivot":"0"}',
                'order' => 6,
            ),
            69 => 
            array (
                'id' => 145,
                'data_type_id' => 10,
                'field' => 'customer_belongsto_how_did_find_out_relationship',
                'type' => 'relationship',
                'display_name' => 'Como ficou sabendo do Namastê?',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\HowDidFindOut","table":"how_did_find_outs","type":"belongsToMany","column":"id","key":"id","label":"lable","pivot_table":"how_did_find_out_customer","pivot":"1"}',
                'order' => 24,
            ),
            70 => 
            array (
                'id' => 146,
                'data_type_id' => 10,
                'field' => 'how_did_find_out_id',
                'type' => 'hidden',
                'display_name' => 'How Did Find Out Id',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 19,
            ),
            71 => 
            array (
                'id' => 147,
                'data_type_id' => 14,
                'field' => 'id',
                'type' => 'checkbox',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 1,
            ),
            72 => 
            array (
                'id' => 148,
                'data_type_id' => 14,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Nome',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 2,
            ),
            73 => 
            array (
                'id' => 149,
                'data_type_id' => 14,
                'field' => 'sannyas',
                'type' => 'text',
                'display_name' => 'Sannyas',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 3,
            ),
            74 => 
            array (
                'id' => 150,
                'data_type_id' => 14,
                'field' => 'created_id',
                'type' => 'hidden',
                'display_name' => 'Created Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 5,
            ),
            75 => 
            array (
                'id' => 151,
                'data_type_id' => 14,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 6,
            ),
            76 => 
            array (
                'id' => 152,
                'data_type_id' => 14,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 7,
            ),
            77 => 
            array (
                'id' => 153,
                'data_type_id' => 14,
                'field' => 'updated_id',
                'type' => 'hidden',
                'display_name' => 'Updated Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 8,
            ),
            78 => 
            array (
                'id' => 154,
                'data_type_id' => 10,
                'field' => 'professional_id',
                'type' => 'hidden',
                'display_name' => 'Professional Id',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 15,
            ),
            79 => 
            array (
                'id' => 155,
                'data_type_id' => 14,
                'field' => 'professional_hasmany_customer_relationship',
                'type' => 'relationship',
                'display_name' => 'Clientes',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Customer","table":"customers","type":"belongsToMany","column":"id","key":"id","label":"name","pivot_table":"professional_customer","pivot":"1"}',
                'order' => 10,
            ),
            80 => 
            array (
                'id' => 156,
                'data_type_id' => 16,
                'field' => 'id',
                'type' => 'checkbox',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 1,
            ),
            81 => 
            array (
                'id' => 157,
                'data_type_id' => 16,
                'field' => 'lable',
                'type' => 'text',
                'display_name' => 'Tipo de profissional',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 2,
            ),
            82 => 
            array (
                'id' => 158,
                'data_type_id' => 16,
                'field' => 'created_id',
                'type' => 'hidden',
                'display_name' => 'Created Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 3,
            ),
            83 => 
            array (
                'id' => 159,
                'data_type_id' => 16,
                'field' => 'updated_id',
                'type' => 'hidden',
                'display_name' => 'Updated Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 4,
            ),
            84 => 
            array (
                'id' => 160,
                'data_type_id' => 16,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Criado em',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 5,
            ),
            85 => 
            array (
                'id' => 161,
                'data_type_id' => 16,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Editado em',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 6,
            ),
            86 => 
            array (
                'id' => 162,
                'data_type_id' => 16,
                'field' => 'professional_type_belongsto_user_relationship',
                'type' => 'relationship',
                'display_name' => 'Criado por',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{"model":"App\\\\User","table":"users","type":"belongsTo","column":"created_id","key":"id","label":"name","pivot_table":"customer_types","pivot":"0"}',
                'order' => 7,
            ),
            87 => 
            array (
                'id' => 163,
                'data_type_id' => 16,
                'field' => 'professional_type_belongsto_user_relationship_1',
                'type' => 'relationship',
                'display_name' => 'Editado por último por',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{"model":"App\\\\User","table":"users","type":"belongsTo","column":"updated_id","key":"id","label":"name","pivot_table":"customer_types","pivot":"0"}',
                'order' => 8,
            ),
            88 => 
            array (
                'id' => 164,
                'data_type_id' => 14,
                'field' => 'professional_belongsto_professional_type_relationship',
                'type' => 'relationship',
                'display_name' => 'Tipo',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\ProfessionalType","table":"professional_types","type":"belongsTo","column":"type_id","key":"id","label":"lable","pivot_table":"customer_types","pivot":"0"}',
                'order' => 4,
            ),
            89 => 
            array (
                'id' => 165,
                'data_type_id' => 14,
                'field' => 'type_id',
                'type' => 'hidden',
                'display_name' => 'Type Id',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 9,
            ),
            90 => 
            array (
                'id' => 175,
                'data_type_id' => 18,
                'field' => 'id',
                'type' => 'hidden',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 1,
            ),
            91 => 
            array (
                'id' => 177,
                'data_type_id' => 18,
                'field' => 'event_id',
                'type' => 'hidden',
                'display_name' => 'Event Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => NULL,
                'order' => 11,
            ),
            92 => 
            array (
                'id' => 178,
                'data_type_id' => 18,
                'field' => 'created_id',
                'type' => 'hidden',
                'display_name' => 'Created Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 2,
            ),
            93 => 
            array (
                'id' => 179,
                'data_type_id' => 18,
                'field' => 'updated_id',
                'type' => 'hidden',
                'display_name' => 'Updated Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 3,
            ),
            94 => 
            array (
                'id' => 180,
                'data_type_id' => 18,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Criado em',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{"format":"%d/%m/%Y %X"}',
                'order' => 6,
            ),
            95 => 
            array (
                'id' => 181,
                'data_type_id' => 18,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Editado em',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{"format":"%d/%m/%Y %X"}',
                'order' => 4,
            ),
            96 => 
            array (
                'id' => 182,
                'data_type_id' => 18,
                'field' => 'participation_belongsto_event_relationship_1',
                'type' => 'relationship',
                'display_name' => 'Evento',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Event","table":"events","type":"belongsTo","column":"event_id","key":"id","label":"name","pivot_table":"customer_types","pivot":"0"}',
                'order' => 5,
            ),
            97 => 
            array (
                'id' => 183,
                'data_type_id' => 18,
                'field' => 'participation_belongsto_customer_relationship_1',
                'type' => 'relationship',
                'display_name' => 'Clientes',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Customer","table":"customers","type":"belongsToMany","column":"id","key":"id","label":"name","pivot_table":"customer_participation","pivot":"1"}',
                'order' => 7,
            ),
            98 => 
            array (
                'id' => 184,
                'data_type_id' => 18,
                'field' => 'participation_belongsto_user_relationship',
                'type' => 'relationship',
                'display_name' => 'Criado por',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{"model":"App\\\\User","table":"users","type":"belongsTo","column":"created_id","key":"id","label":"name","pivot_table":"customer_types","pivot":"0"}',
                'order' => 8,
            ),
            99 => 
            array (
                'id' => 185,
                'data_type_id' => 18,
                'field' => 'participation_belongsto_user_relationship_1',
                'type' => 'relationship',
                'display_name' => 'Editado por último por',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{"model":"App\\\\User","table":"users","type":"belongsTo","column":"updated_id","key":"id","label":"name","pivot_table":"customer_types","pivot":"0"}',
                'order' => 9,
            ),
            100 => 
            array (
                'id' => 187,
                'data_type_id' => 18,
                'field' => 'participation_belongstomany_professional_relationship',
                'type' => 'relationship',
                'display_name' => 'Profissionais',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Professional","table":"professionals","type":"belongsToMany","column":"id","key":"id","label":"sannyas","pivot_table":"customer_participation","pivot":"1"}',
                'order' => 10,
            ),
            101 => 
            array (
                'id' => 190,
                'data_type_id' => 18,
                'field' => 'start_date',
                'type' => 'date',
                'display_name' => 'Data de Início',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"format":"%d/%m/%Y %X","display":{"width":"6"}}',
                'order' => 12,
            ),
            102 => 
            array (
                'id' => 191,
                'data_type_id' => 18,
                'field' => 'end_date',
                'type' => 'date',
                'display_name' => 'Data de Término',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"format":"%d/%m/%Y %X","display":{"width":"6"}}',
                'order' => 13,
            ),
            103 => 
            array (
                'id' => 198,
                'data_type_id' => 19,
                'field' => 'id',
                'type' => 'hidden',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 1,
            ),
            104 => 
            array (
                'id' => 199,
                'data_type_id' => 19,
                'field' => 'path',
                'type' => 'file',
                'display_name' => 'Arquivo',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 4,
            ),
            105 => 
            array (
                'id' => 200,
                'data_type_id' => 19,
                'field' => 'title',
                'type' => 'text',
                'display_name' => 'Título',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 3,
            ),
            106 => 
            array (
                'id' => 201,
                'data_type_id' => 19,
                'field' => 'active',
                'type' => 'checkbox',
                'display_name' => 'Ativo?',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"on":"Sim","off":"Não","checked":"true"}',
                'order' => 5,
            ),
            107 => 
            array (
                'id' => 202,
                'data_type_id' => 19,
                'field' => 'customer_id',
                'type' => 'hidden',
                'display_name' => 'Customer Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 6,
            ),
            108 => 
            array (
                'id' => 203,
                'data_type_id' => 19,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Criado em',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 0,
                'delete' => 1,
                'details' => '{"format":"%d/%m/%Y %X"}',
                'order' => 7,
            ),
            109 => 
            array (
                'id' => 204,
                'data_type_id' => 19,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Editado em',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{"format":"%d/%m/%Y %X"}',
                'order' => 8,
            ),
            110 => 
            array (
                'id' => 205,
                'data_type_id' => 19,
                'field' => 'attachment_belongsto_customer_relationship',
                'type' => 'relationship',
                'display_name' => 'Cliente',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Customer","table":"customers","type":"belongsTo","column":"customer_id","key":"id","label":"name","pivot_table":"attachments","pivot":"0"}',
                'order' => 2,
            ),
            111 => 
            array (
                'id' => 206,
                'data_type_id' => 10,
                'field' => 'customer_hasmany_attachment_relationship',
                'type' => 'relationship',
                'display_name' => 'Arquivos',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Attachment","table":"attachments","type":"hasMany","column":"customer_id","key":"id","label":"path","pivot_table":"attachments","pivot":"0"}',
                'order' => 25,
            ),
            112 => 
            array (
                'id' => 207,
                'data_type_id' => 22,
                'field' => 'id',
                'type' => 'checkbox',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 1,
            ),
            113 => 
            array (
                'id' => 208,
                'data_type_id' => 22,
                'field' => 'label',
                'type' => 'text',
                'display_name' => 'Tipo de evento',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 2,
            ),
            114 => 
            array (
                'id' => 209,
                'data_type_id' => 22,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Criado em',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 3,
            ),
            115 => 
            array (
                'id' => 210,
                'data_type_id' => 22,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Editado em',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 4,
            ),
            116 => 
            array (
                'id' => 211,
                'data_type_id' => 23,
                'field' => 'id',
                'type' => 'checkbox',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 1,
            ),
            117 => 
            array (
                'id' => 212,
                'data_type_id' => 23,
                'field' => 'label',
                'type' => 'text',
                'display_name' => 'Classificação do evento',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 2,
            ),
            118 => 
            array (
                'id' => 213,
                'data_type_id' => 23,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Criado em',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 3,
            ),
            119 => 
            array (
                'id' => 214,
                'data_type_id' => 23,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Editado em',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 4,
            ),
            120 => 
            array (
                'id' => 215,
                'data_type_id' => 8,
                'field' => 'event_belongsto_event_classification_relationship',
                'type' => 'relationship',
                'display_name' => 'Classificação do evento',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\EventClassification","table":"event_classifications","type":"belongsTo","column":"event_classification_id","key":"id","label":"label","pivot_table":"attachments","pivot":"0"}',
                'order' => 3,
            ),
            121 => 
            array (
                'id' => 216,
                'data_type_id' => 8,
                'field' => 'event_classification_id',
                'type' => 'hidden',
                'display_name' => 'Event Classification Id',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 4,
            ),
            122 => 
            array (
                'id' => 217,
                'data_type_id' => 23,
                'field' => 'event_classification_hasmany_event_relationship',
                'type' => 'relationship',
                'display_name' => 'Eventos',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{"model":"App\\\\Event","table":"events","type":"hasMany","column":"event_classification_id","key":"id","label":"name","pivot_table":"attachments","pivot":"0"}',
                'order' => 5,
            ),
        ));
        
        
    }
}