runtime: php
env: flex

runtime_config:
  document_root: public

# Ensure we skip ".env", which is only for local development
skip_files:
  .env

env_variables:
  # Put production environment variables here.
  APP_LOG: errorlog
  APP_DEBUG: true
  APP_KEY: base64:9LGq2Y7KxeB92MDlW89d2nP3Si9euHWdaTn7+Me95fc=
  STORAGE_DIR: /tmp
  CACHE_DRIVER: file
  SESSION_DRIVER: file
  DB_CONNECTION: mysql
  DB_HOST: localhost
  DB_PORT: 3307
  DB_DATABASE: reception
  DB_USERNAME: reception
  DB_PASSWORD: reception
  DB_SOCKET: "/cloudsql/recepcao-namaste-201319:us-central1:mysql"

beta_settings:
  cloud_sql_instances: "recepcao-namaste-201319:us-central1:mysql"