runtime: php
env: flex

runtime_config:
  document_root: public

# Ensure we skip ".env", which is only for local development
skip_files:
  - .env
  
env_variables:
  # Put production environment variables here.
  APP_LOG: errorlog
  APP_DEBUG: true
  APP_KEY: base64:9LGq2Y7KxeB92MDlW89d2nP3Si9euHWdaTn7+Me95fc=
  APP_ENV: production
  STORAGE_DIR: /tmp
  CACHE_DRIVER: database
  SESSION_DRIVER: database
  
  DB_CONNECTION: mysql
  DB_HOST: localhost
  DB_DATABASE: mysql
  DB_USERNAME: root
  DB_PASSWORD: root
  DB_SOCKET: /cloudsql/recepcao-namaste-201319:us-central1:mysql

beta_settings:
  cloud_sql_instances: recepcao-namaste-201319:us-central1:mysql